name: Build Cover Letter
description: Compile LaTeX Cover Letter & upload artifact

runs:
  using: "composite"
  steps:
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: coverletter.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: Cover Letter
        path: coverletter.pdf
