name: Build Resume
description: Compile LaTeX Resume & upload artifact

runs:
  using: "composite"
  steps:
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: Resume
        path: resume.pdf
        
    - name: Upload to gdrive
      uses: adityak74/google-drive-upload-git-action@main
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        FOLDER_ID: ${{ secrets.FOLDER_ID }}
      with:
        credentials: $GOOGLE_DRIVE_CREDENTIALS
        filename: "resume.pdf"
        folderId: $FOLDER_ID
