name: Build Resume
description: Compile LaTeX Resume & upload artifact

inputs:
  credentials:
    description: Google Drive credentials
    required: true
  folderId:
    description: Folder ID
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: Resume
        path: resume.pdf
        
    - name: Upload to gdrive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ inputs.credentials }}
        filename: "resume.pdf"
        folderId: ${{ inputs.folderId }}
