name: Build PDF
description: Compile LaTeX PDF & upload artifact

inputs:
  file:
    description: LaTex filename to compile
    required: true
  output:
    description: Output PDF filename
    required: true
  credentials:
    description: Google Drive credentials
    required: true
  folderId:
    description: Folder ID
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ${{ inputs.file }}.tex
        
    - name: Rename PDF file
      run: mv ${{ inputs.file }}.pdf ${{ inputs.output }}
      shell: bash
      
    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: Resume
        path: ${{ inputs.output }}
        
    - name: Upload to Google Drive
      uses: willo32/google-drive-upload-action@v1
      with:
        credentials: ${{ inputs.credentials }}
        parent_folder_id: ${{ inputs.folderId }}
        target: "Jed Abanat Resume.pdf"
        child_folder: ${{ github.base_ref || github.ref_name }}
