name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "Jed Abanat Resume.tex"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "Jed Abanat Resume.pdf"
          
      - uses: actions/download-artifact@v3
        
      - name: Display structure of downloaded files
        run: ls -R
