name: Build LaTeX document
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Checkout
        uses: actions/checkout@v4

      - name: Build Resume
        uses: ./.github/composite/build-resume

      - name: Build Cover Letter
        uses: ./.github/composite/build-coverletter