name: Build LaTeX documents
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Checkout
        uses: actions/checkout@v4

      - name: Compile Resume
        uses: ./.github/composite/compile-latex-pdf
        with:
          latex_file: "resume"
          pdf_file: "Jed Abanat Resume.pdf"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folderId: ${{ secrets.FOLDER_ID }}

      - name: Compile Cover Letter
        uses: ./.github/composite/compile-latex-pdf
        with:
          latex_file: "coverletter"
          pdf_file: "Jed Abanat Cover Letter.pdf"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folderId: ${{ secrets.FOLDER_ID }}