name: Build LaTeX document
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Checkout
        uses: actions/checkout@v3

      - name: Build
      - uses: ./.github/composite/build
