name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Setup & Checkout
        uses: actions/checkout@v3
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume.pdf
          
      - uses: actions/download-artifact@v3
        
      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PDF

      # Replace latest release
      - name: Cleanup releases
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          tag_name: latest
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Resume
          body: My latest resume
          draft: false
          files: |
            resume.pdf
